log4j.logger.com.MusicApp.com.novi.app.model.dao.impl.UserDAOImpl=INFO, stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout